
// #define DEBUG


/* 通过位操作来实现逆序 */
unsigned int reverse_bits(unsigned int val) {
	int i = 0;
	unsigned res = 0;
	int bits = sizeof(val) * 8;

	/* 作者的解决方案是巧妙运用1的移位 */
	/* for (int i = 1; i != 0; i <<= 1) */

	while (i < bits-1) {
		res |= val & 1;
		res <<= 1;
		val >>= 1;
		i++;

	}

	return (unsigned int)res;
}

#ifdef DEBUG

#include <stdio.h>

/* Generated By ChartGPT */
void printBinary(unsigned int num) {
    int size = sizeof(num) * 8; // 获取整数的位数

    for (int i = size - 1; i >= 0; i--) {
        int bit = (num >> i) & 1; // 通过右移和与操作获取每一位的值
        printf("%d", bit);
    }

    printf("\n");
}

int main() {
	unsigned a = 25;
	unsigned b = reverse_bits(a);
	printBinary(a);
	printBinary(b);
}

#endif