#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

/* Generated By ChartGPT */
/* 巧妙地使用了堆栈的概念进行配对 */


// Define a simple stack structure for tracking braces
typedef struct {
	char *data;
	size_t capacity;
	size_t size;
} Stack;

// Function to initialize the stack
void initStack(Stack *stack, size_t capacity) {
	stack->data = (char *)malloc(capacity * sizeof(char));
	stack->capacity = capacity;
	stack->size = 0;
}

// Function to push a character onto the stack
void push(Stack *stack, char c) {
	if (stack->size < stack->capacity) {
		stack->data[stack->size++] = c;
	}
}

// Function to pop a character from the stack
char pop(Stack *stack) {
	if (stack->size > 0) {
		return stack->data[--stack->size];
	}
	return '\0'; // Return null character for an empty stack
}

// Function to check if the stack is empty
bool isEmpty(Stack *stack) {
    	return stack->size == 0;
}

int main() {
	int ch;
	Stack braceStack;
	initStack(&braceStack, 100); // Adjust the capacity as needed

	while ((ch = getchar()) != EOF) {
		if (ch == '/') {
		// Check for comments
		int nextChar = getchar();
		if (nextChar == '*') {
			// Skip characters until the end of the comment
			while ((ch = getchar()) != '*' || (nextChar = getchar()) != '/') {
			if (ch == EOF || nextChar == EOF) {
				fprintf(stderr, "Error: Unclosed comment\n");
				return 1;
			}
			}
			continue; // Continue to the next character after the comment
		} else {
			ungetc(nextChar, stdin); // Put the character back
		}
		}

		if (ch == '\'' || ch == '\"') {
		// Skip characters within single or double quotes
		int quoteChar = ch;
		while ((ch = getchar()) != quoteChar) {
			if (ch == '\\') {
			// Skip escaped characters
			getchar();
			}
			if (ch == EOF) {
			fprintf(stderr, "Error: Unclosed string literal\n");
			return 1;
			}
		}
		}

		if (ch == '{') {
		// Push opening brace onto the stack
		push(&braceStack, ch);
		} else if (ch == '}') {
		// Check for a matching opening brace on the stack
		if (isEmpty(&braceStack) || pop(&braceStack) != '{') {
			fprintf(stdout, "Not correctly paired: }\n");
			return 1;
		}
		}
	}

	// Check if there are unmatched opening braces on the stack
	if (!isEmpty(&braceStack)) {
		fprintf(stdout, "Not correctly paired: {\n");
		return 1;
	}

	fprintf(stdout, "All braces are correctly paired!\n");

	return 0;
}
